// Generated by gencpp from file new_project/output.msg
// DO NOT EDIT!


#ifndef NEW_PROJECT_MESSAGE_OUTPUT_H
#define NEW_PROJECT_MESSAGE_OUTPUT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace new_project
{
template <class ContainerAllocator>
struct output_
{
  typedef output_<ContainerAllocator> Type;

  output_()
    : output(0.0)
    , status(false)  {
    }
  output_(const ContainerAllocator& _alloc)
    : output(0.0)
    , status(false)  {
  (void)_alloc;
    }



   typedef double _output_type;
  _output_type output;

   typedef uint8_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::new_project::output_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::new_project::output_<ContainerAllocator> const> ConstPtr;

}; // struct output_

typedef ::new_project::output_<std::allocator<void> > output;

typedef boost::shared_ptr< ::new_project::output > outputPtr;
typedef boost::shared_ptr< ::new_project::output const> outputConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::new_project::output_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::new_project::output_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace new_project

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'new_project': ['/home/notanshuman/catkin_ws/src/new_project/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::new_project::output_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::new_project::output_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::new_project::output_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::new_project::output_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::new_project::output_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::new_project::output_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::new_project::output_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6dc767a0ee3290acb4a8a3c442cafea7";
  }

  static const char* value(const ::new_project::output_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6dc767a0ee3290acULL;
  static const uint64_t static_value2 = 0xb4a8a3c442cafea7ULL;
};

template<class ContainerAllocator>
struct DataType< ::new_project::output_<ContainerAllocator> >
{
  static const char* value()
  {
    return "new_project/output";
  }

  static const char* value(const ::new_project::output_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::new_project::output_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 output\n\
bool status\n\
";
  }

  static const char* value(const ::new_project::output_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::new_project::output_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.output);
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct output_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::new_project::output_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::new_project::output_<ContainerAllocator>& v)
  {
    s << indent << "output: ";
    Printer<double>::stream(s, indent + "  ", v.output);
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NEW_PROJECT_MESSAGE_OUTPUT_H
